"""
Türk İsimleri Veritabanı
5000+ Türk ismi - Erkek, Kız ve Unisex
Her isim için: cinsiyet, köken, popülerlik, islami bilgisi
"""

# İsim formatı: (isim, cinsiyet, köken, popüler, islami)
# cinsiyet: "erkek", "kiz", "unisex"
# köken: "Türkçe", "Arapça", "Farsça", "Diğer"
# popüler: True/False
# islami: True/False

ERKEK_ISIMLERI = [
    # A harfi
    ("Aamir", "Arapça", False, True),
    ("Abbas", "Arapça", False, True),
    ("Abdulaziz", "Arapça", False, True),
    ("Abdullah", "Arapça", True, True),
    ("Abdulkadir", "Arapça", False, True),
    ("Abdulmuttalip", "Arapça", False, True),
    ("Abdurrahman", "Arapça", True, True),
    ("Abdurrezzak", "Arapça", False, True),
    ("Abdulsamet", "Arapça", False, True),
    ("Abidin", "Arapça", False, True),
    ("Aclan", "Türkçe", False, False),
    ("Acar", "Türkçe", False, False),
    ("Adalet", "Arapça", False, False),
    ("Adem", "Arapça", True, True),
    ("Adıgüzel", "Türkçe", False, False),
    ("Adil", "Arapça", False, True),
    ("Adnan", "Arapça", True, True),
    ("Afşin", "Türkçe", False, False),
    ("Agah", "Farsça", False, False),
    ("Ağabey", "Türkçe", False, False),
    ("Ahmet", "Arapça", True, True),
    ("Akay", "Türkçe", False, False),
    ("Akbatur", "Türkçe", False, False),
    ("Akdemir", "Türkçe", False, False),
    ("Akgün", "Türkçe", False, False),
    ("Akhan", "Türkçe", False, False),
    ("Akif", "Arapça", False, True),
    ("Akin", "Türkçe", False, False),
    ("Akın", "Türkçe", True, False),
    ("Akkuş", "Türkçe", False, False),
    ("Akman", "Türkçe", False, False),
    ("Akyüz", "Türkçe", False, False),
    ("Alaaddin", "Arapça", False, True),
    ("Alaattin", "Arapça", False, True),
    ("Alaz", "Türkçe", False, False),
    ("Albayrak", "Türkçe", False, False),
    ("Ali", "Arapça", True, True),
    ("Alican", "Türkçe", True, False),
    ("Alihan", "Türkçe", False, False),
    ("Alim", "Arapça", False, True),
    ("Alişan", "Türkçe", False, False),
    ("Alp", "Türkçe", True, False),
    ("Alparslan", "Türkçe", True, False),
    ("Alpay", "Türkçe", True, False),
    ("Alper", "Türkçe", True, False),
    ("Alperen", "Türkçe", True, False),
    ("Alphan", "Türkçe", False, False),
    ("Altan", "Türkçe", True, False),
    ("Altay", "Türkçe", True, False),
    ("Altın", "Türkçe", False, False),
    ("Altınay", "Türkçe", False, False),
    ("Anil", "Türkçe", False, False),
    ("Anıl", "Türkçe", True, False),
    ("Arat", "Türkçe", False, False),
    ("Aras", "Türkçe", True, False),
    ("Arda", "Türkçe", True, False),
    ("Argun", "Türkçe", False, False),
    ("Arhan", "Türkçe", False, False),
    ("Arif", "Arapça", True, True),
    ("Arkın", "Türkçe", False, False),
    ("Armağan", "Türkçe", False, False),
    ("Arslan", "Türkçe", True, False),
    ("Asaf", "Arapça", False, True),
    ("Asım", "Arapça", False, True),
    ("Asker", "Arapça", False, False),
    ("Aslan", "Türkçe", True, False),
    ("Ata", "Türkçe", True, False),
    ("Ataberk", "Türkçe", False, False),
    ("Atabey", "Türkçe", False, False),
    ("Atacan", "Türkçe", False, False),
    ("Atahan", "Türkçe", False, False),
    ("Atakan", "Türkçe", True, False),
    ("Atalay", "Türkçe", True, False),
    ("Ataman", "Türkçe", False, False),
    ("Atasoy", "Türkçe", False, False),
    ("Atıf", "Arapça", False, True),
    ("Atıl", "Türkçe", False, False),
    ("Atila", "Türkçe", False, False),
    ("Atilla", "Türkçe", True, False),
    ("Avni", "Arapça", False, True),
    ("Ayaz", "Türkçe", True, False),
    ("Aydemir", "Türkçe", False, False),
    ("Aydın", "Türkçe", True, False),
    ("Aydoğan", "Türkçe", False, False),
    ("Ayhan", "Türkçe", True, False),
    ("Aykut", "Türkçe", True, False),
    ("Aytaç", "Türkçe", True, False),
    ("Aytunç", "Türkçe", False, False),
    ("Azad", "Farsça", False, False),
    ("Azat", "Farsça", False, False),
    ("Azim", "Arapça", False, True),
    ("Aziz", "Arapça", True, True),
    ("Azmi", "Arapça", False, True),

    # B harfi
    ("Bahadır", "Türkçe", True, False),
    ("Bahaddin", "Arapça", False, True),
    ("Bahri", "Arapça", False, True),
    ("Baki", "Arapça", True, True),
    ("Baran", "Farsça", True, False),
    ("Barış", "Türkçe", True, False),
    ("Barlas", "Türkçe", False, False),
    ("Barkın", "Türkçe", False, False),
    ("Başar", "Türkçe", True, False),
    ("Batı", "Türkçe", False, False),
    ("Batu", "Türkçe", True, False),
    ("Batuhan", "Türkçe", True, False),
    ("Baykal", "Türkçe", False, False),
    ("Bayram", "Türkçe", True, False),
    ("Bayramalp", "Türkçe", False, False),
    ("Bedirhan", "Türkçe", False, False),
    ("Bedrettin", "Arapça", False, True),
    ("Bedri", "Arapça", False, True),
    ("Behçet", "Arapça", False, True),
    ("Behram", "Farsça", False, False),
    ("Behzat", "Farsça", False, False),
    ("Bekir", "Arapça", True, True),
    ("Bektaş", "Türkçe", False, False),
    ("Berat", "Arapça", True, True),
    ("Berk", "Türkçe", True, False),
    ("Berkalp", "Türkçe", False, False),
    ("Berkan", "Türkçe", True, False),
    ("Berkant", "Türkçe", False, False),
    ("Berkay", "Türkçe", True, False),
    ("Berke", "Türkçe", True, False),
    ("Berker", "Türkçe", False, False),
    ("Berkhan", "Türkçe", False, False),
    ("Berkin", "Türkçe", True, False),
    ("Berksan", "Türkçe", False, False),
    ("Besim", "Arapça", False, True),
    ("Beyazıt", "Türkçe", False, False),
    ("Beysel", "Türkçe", False, False),
    ("Bilal", "Arapça", True, True),
    ("Bilge", "Türkçe", True, False),
    ("Bilgehan", "Türkçe", False, False),
    ("Bilgin", "Türkçe", False, False),
    ("Birant", "Türkçe", False, False),
    ("Bircan", "Türkçe", False, False),
    ("Birhan", "Türkçe", False, False),
    ("Birkan", "Türkçe", False, False),
    ("Birsel", "Türkçe", False, False),
    ("Boğaç", "Türkçe", False, False),
    ("Bora", "Türkçe", True, False),
    ("Boran", "Türkçe", True, False),
    ("Boyraz", "Türkçe", False, False),
    ("Bülent", "Türkçe", True, False),
    ("Buğra", "Türkçe", True, False),
    ("Buğrahan", "Türkçe", False, False),
    ("Burak", "Arapça", True, True),
    ("Burç", "Türkçe", False, False),
    ("Burçin", "Türkçe", False, False),
    ("Burhan", "Arapça", True, True),
    ("Burkay", "Türkçe", False, False),

    # C harfi
    ("Cabbar", "Arapça", False, True),
    ("Cafer", "Arapça", True, True),
    ("Cahit", "Arapça", True, True),
    ("Can", "Farsça", True, False),
    ("Canalp", "Türkçe", False, False),
    ("Canberk", "Türkçe", False, False),
    ("Caner", "Türkçe", True, False),
    ("Canip", "Arapça", False, True),
    ("Canpolat", "Türkçe", False, False),
    ("Cavit", "Arapça", False, True),
    ("Cebrail", "Arapça", False, True),
    ("Celal", "Arapça", True, True),
    ("Celalettin", "Arapça", False, True),
    ("Celil", "Arapça", False, True),
    ("Cem", "Farsça", True, False),
    ("Cemal", "Arapça", True, True),
    ("Cemalettin", "Arapça", False, True),
    ("Cemil", "Arapça", True, True),
    ("Cenap", "Arapça", False, True),
    ("Cenay", "Türkçe", False, False),
    ("Cengiz", "Türkçe", True, False),
    ("Cengizhan", "Türkçe", False, False),
    ("Cenk", "Farsça", True, False),
    ("Cevad", "Arapça", False, True),
    ("Cevahir", "Arapça", False, True),
    ("Cevat", "Arapça", True, True),
    ("Cevdet", "Arapça", True, True),
    ("Cezmi", "Arapça", False, True),
    ("Cihan", "Farsça", True, False),
    ("Cihanşah", "Farsça", False, False),
    ("Cihangir", "Farsça", False, False),
    ("Coşkun", "Türkçe", True, False),
    ("Coşkuner", "Türkçe", False, False),
    ("Cumali", "Arapça", False, True),
    ("Cumhur", "Arapça", False, False),
    ("Cüneyt", "Arapça", True, True),

    # Ç harfi
    ("Çağan", "Türkçe", True, False),
    ("Çağatay", "Türkçe", True, False),
    ("Çağdaş", "Türkçe", True, False),
    ("Çağın", "Türkçe", False, False),
    ("Çağlar", "Türkçe", True, False),
    ("Çağrı", "Türkçe", True, False),
    ("Çakır", "Türkçe", False, False),
    ("Çelen", "Türkçe", False, False),
    ("Çelebi", "Türkçe", False, False),
    ("Çelik", "Türkçe", False, False),
    ("Çetin", "Türkçe", True, False),
    ("Çetinalp", "Türkçe", False, False),
    ("Çetiner", "Türkçe", False, False),
    ("Çınar", "Türkçe", True, False),

    # D harfi
    ("Dağhan", "Türkçe", False, False),
    ("Daner", "Türkçe", False, False),
    ("Davut", "Arapça", True, True),
    ("Demir", "Türkçe", True, False),
    ("Demiralp", "Türkçe", False, False),
    ("Demiray", "Türkçe", False, False),
    ("Demircan", "Türkçe", False, False),
    ("Demirhan", "Türkçe", False, False),
    ("Demirtaş", "Türkçe", False, False),
    ("Deniz", "Türkçe", True, False),
    ("Denizalp", "Türkçe", False, False),
    ("Denizhan", "Türkçe", False, False),
    ("Derviş", "Farsça", False, True),
    ("Devrim", "Türkçe", True, False),
    ("Doğa", "Türkçe", True, False),
    ("Doğan", "Türkçe", True, False),
    ("Doğanalp", "Türkçe", False, False),
    ("Doğanay", "Türkçe", False, False),
    ("Doğuhan", "Türkçe", True, False),
    ("Doruk", "Türkçe", True, False),
    ("Duhan", "Arapça", False, True),
    ("Duman", "Türkçe", False, False),
    ("Durmuş", "Türkçe", True, False),
    ("Dursun", "Türkçe", True, False),

    # E harfi
    ("Ebubekir", "Arapça", True, True),
    ("Ecevit", "Türkçe", False, False),
    ("Ece", "Türkçe", False, False),
    ("Ecmel", "Arapça", False, True),
    ("Edip", "Arapça", False, True),
    ("Ediz", "Türkçe", True, False),
    ("Efkan", "Türkçe", False, False),
    ("Efe", "Türkçe", True, False),
    ("Efecan", "Türkçe", True, False),
    ("Efehan", "Türkçe", False, False),
    ("Eflal", "Arapça", False, True),
    ("Egemen", "Türkçe", True, False),
    ("Ekber", "Arapça", False, True),
    ("Ekmel", "Arapça", False, True),
    ("Ekrem", "Arapça", True, True),
    ("Elvan", "Türkçe", False, False),
    ("Emek", "Türkçe", False, False),
    ("Emin", "Arapça", True, True),
    ("Emir", "Arapça", True, True),
    ("Emiralp", "Türkçe", False, False),
    ("Emircan", "Türkçe", True, False),
    ("Emirhan", "Türkçe", True, False),
    ("Emrah", "Türkçe", True, False),
    ("Emre", "Türkçe", True, False),
    ("Emrullah", "Arapça", False, True),
    ("Ender", "Türkçe", True, False),
    ("Enes", "Arapça", True, True),
    ("Engin", "Türkçe", True, False),
    ("Ensar", "Arapça", True, True),
    ("Enver", "Arapça", True, True),
    ("Eray", "Türkçe", True, False),
    ("Ercan", "Türkçe", True, False),
    ("Ercüment", "Farsça", False, False),
    ("Erdal", "Türkçe", True, False),
    ("Erdem", "Türkçe", True, False),
    ("Erdinç", "Türkçe", True, False),
    ("Erdoğan", "Türkçe", True, False),
    ("Eren", "Türkçe", True, False),
    ("Erenalp", "Türkçe", False, False),
    ("Erencan", "Türkçe", False, False),
    ("Ergin", "Türkçe", True, False),
    ("Ergün", "Türkçe", True, False),
    ("Erhan", "Türkçe", True, False),
    ("Erkam", "Arapça", False, True),
    ("Erkan", "Türkçe", True, False),
    ("Erkmen", "Türkçe", False, False),
    ("Erkut", "Türkçe", False, False),
    ("Erol", "Türkçe", True, False),
    ("Ersan", "Türkçe", True, False),
    ("Ersin", "Türkçe", True, False),
    ("Ertan", "Türkçe", True, False),
    ("Ertuğrul", "Türkçe", True, False),
    ("Esat", "Arapça", True, True),
    ("Eslem", "Arapça", False, True),
    ("Ethem", "Arapça", False, True),
    ("Evren", "Türkçe", True, False),
    ("Evrensel", "Türkçe", False, False),
    ("Eymen", "Arapça", True, True),
    ("Eyüp", "Arapça", True, True),
    ("Ezel", "Arapça", False, True),

    # F harfi
    ("Fadıl", "Arapça", False, True),
    ("Fahrettin", "Arapça", False, True),
    ("Fahri", "Arapça", True, True),
    ("Faik", "Arapça", False, True),
    ("Faruk", "Arapça", True, True),
    ("Fatih", "Arapça", True, True),
    ("Faysal", "Arapça", False, True),
    ("Fazıl", "Arapça", True, True),
    ("Fehim", "Arapça", False, True),
    ("Fehmi", "Arapça", False, True),
    ("Feraset", "Arapça", False, True),
    ("Ferman", "Farsça", False, False),
    ("Ferruh", "Arapça", False, True),
    ("Ferit", "Arapça", True, True),
    ("Ferhan", "Farsça", False, False),
    ("Ferhat", "Farsça", True, False),
    ("Ferman", "Farsça", False, False),
    ("Fethi", "Arapça", True, True),
    ("Fevzi", "Arapça", True, True),
    ("Feyyaz", "Arapça", False, True),
    ("Fikret", "Arapça", True, True),
    ("Fikri", "Arapça", False, True),
    ("Fuat", "Arapça", True, True),
    ("Furkan", "Arapça", True, True),

    # G harfi
    ("Galip", "Arapça", True, True),
    ("Gani", "Arapça", False, True),
    ("Gazi", "Arapça", True, True),
    ("Gencer", "Türkçe", False, False),
    ("Gençer", "Türkçe", False, False),
    ("Giray", "Türkçe", False, False),
    ("Gökay", "Türkçe", False, False),
    ("Gökberk", "Türkçe", True, False),
    ("Gökhan", "Türkçe", True, False),
    ("Gökmen", "Türkçe", False, False),
    ("Göksel", "Türkçe", True, False),
    ("Göktürk", "Türkçe", False, False),
    ("Görkem", "Türkçe", True, False),
    ("Güçlü", "Türkçe", False, False),
    ("Gültekin", "Türkçe", False, False),
    ("Günden", "Türkçe", False, False),
    ("Güner", "Türkçe", False, False),
    ("Güneş", "Türkçe", True, False),
    ("Güney", "Türkçe", True, False),
    ("Günhan", "Türkçe", False, False),
    ("Güngör", "Türkçe", False, False),
    ("Gürbüz", "Türkçe", True, False),
    ("Gürhan", "Türkçe", True, False),
    ("Gürkan", "Türkçe", True, False),
    ("Gürsel", "Türkçe", True, False),
    ("Güven", "Türkçe", True, False),
    ("Güvenç", "Türkçe", False, False),

    # H harfi
    ("Habib", "Arapça", False, True),
    ("Hacı", "Arapça", True, True),
    ("Hadi", "Arapça", False, True),
    ("Hafız", "Arapça", False, True),
    ("Hakan", "Türkçe", True, False),
    ("Hakim", "Arapça", False, True),
    ("Hakkı", "Arapça", True, True),
    ("Haldun", "Arapça", False, True),
    ("Halil", "Arapça", True, True),
    ("Halim", "Arapça", False, True),
    ("Halit", "Arapça", True, True),
    ("Haluk", "Arapça", True, True),
    ("Hamdi", "Arapça", True, True),
    ("Hamit", "Arapça", True, True),
    ("Hamza", "Arapça", True, True),
    ("Hanefi", "Arapça", False, True),
    ("Hanifi", "Arapça", False, True),
    ("Hasan", "Arapça", True, True),
    ("Haşim", "Arapça", False, True),
    ("Haşmet", "Arapça", False, True),
    ("Hayati", "Arapça", True, True),
    ("Haydar", "Arapça", True, True),
    ("Hayrettin", "Arapça", False, True),
    ("Hayri", "Arapça", True, True),
    ("Hazım", "Arapça", False, True),
    ("Hidayet", "Arapça", False, True),
    ("Hikmet", "Arapça", True, True),
    ("Hilmi", "Arapça", True, True),
    ("Hüdaverdi", "Farsça", False, True),
    ("Hüseyin", "Arapça", True, True),
    ("Hüsnü", "Arapça", False, True),

    # I-İ harfi
    ("Işık", "Türkçe", False, False),
    ("İbrahim", "Arapça", True, True),
    ("İdris", "Arapça", True, True),
    ("İhsan", "Arapça", True, True),
    ("İlhan", "Türkçe", True, False),
    ("İlhami", "Arapça", False, True),
    ("İlkay", "Türkçe", True, False),
    ("İlker", "Türkçe", True, False),
    ("İlyas", "Arapça", True, True),
    ("İmam", "Arapça", False, True),
    ("İnan", "Türkçe", False, False),
    ("İrfan", "Arapça", True, True),
    ("İsa", "Arapça", True, True),
    ("İshak", "Arapça", True, True),
    ("İskender", "Diğer", True, False),
    ("İslam", "Arapça", True, True),
    ("İsmail", "Arapça", True, True),
    ("İsmet", "Arapça", True, True),
    ("İsrafil", "Arapça", False, True),
    ("İzzettin", "Arapça", False, True),

    # K harfi
    ("Kaan", "Türkçe", True, False),
    ("Kadir", "Arapça", True, True),
    ("Kadri", "Arapça", False, True),
    ("Kağan", "Türkçe", True, False),
    ("Kamber", "Arapça", False, True),
    ("Kamil", "Arapça", True, True),
    ("Kamuran", "Farsça", False, False),
    ("Kani", "Arapça", False, True),
    ("Kaplan", "Türkçe", False, False),
    ("Karahan", "Türkçe", True, False),
    ("Karakaya", "Türkçe", False, False),
    ("Kartal", "Türkçe", True, False),
    ("Kasım", "Arapça", True, True),
    ("Kaya", "Türkçe", True, False),
    ("Kayahan", "Türkçe", True, False),
    ("Kayhan", "Türkçe", True, False),
    ("Kazım", "Arapça", True, True),
    ("Kemal", "Arapça", True, True),
    ("Kemalettin", "Arapça", False, True),
    ("Kenan", "Arapça", True, True),
    ("Kerem", "Arapça", True, True),
    ("Kerim", "Arapça", True, True),
    ("Kıvanç", "Türkçe", True, False),
    ("Kıyas", "Arapça", False, True),
    ("Koray", "Türkçe", True, False),
    ("Korkut", "Türkçe", True, False),
    ("Korhan", "Türkçe", True, False),
    ("Kudret", "Arapça", False, True),
    ("Kurtuluş", "Türkçe", True, False),
    ("Kutay", "Türkçe", True, False),
    ("Kutbettin", "Arapça", False, True),
    ("Kuthan", "Türkçe", False, False),
    ("Kutlu", "Türkçe", False, False),
    ("Kutluhan", "Türkçe", False, False),

    # L harfi
    ("Latif", "Arapça", False, True),
    ("Levent", "Türkçe", True, False),
    ("Lokman", "Arapça", True, True),
    ("Lütfi", "Arapça", True, True),
    ("Lütfullah", "Arapça", False, True),

    # M harfi
    ("Macit", "Arapça", False, True),
    ("Mahmut", "Arapça", True, True),
    ("Mahsun", "Arapça", False, True),
    ("Malik", "Arapça", False, True),
    ("Mansur", "Arapça", False, True),
    ("Mazhar", "Arapça", False, True),
    ("Mehmet", "Arapça", True, True),
    ("Melih", "Arapça", True, True),
    ("Menderes", "Diğer", False, False),
    ("Mert", "Türkçe", True, False),
    ("Mertalp", "Türkçe", False, False),
    ("Mertay", "Türkçe", False, False),
    ("Mertcan", "Türkçe", True, False),
    ("Merthan", "Türkçe", False, False),
    ("Mesut", "Arapça", True, True),
    ("Metehan", "Türkçe", True, False),
    ("Metin", "Arapça", True, True),
    ("Mevlüt", "Arapça", True, True),
    ("Mikail", "Arapça", True, True),
    ("Mithat", "Arapça", False, True),
    ("Muammer", "Arapça", False, True),
    ("Mücahit", "Arapça", True, True),
    ("Muhammed", "Arapça", True, True),
    ("Muhittin", "Arapça", False, True),
    ("Muhsin", "Arapça", False, True),
    ("Muhtar", "Arapça", False, True),
    ("Murat", "Arapça", True, True),
    ("Musa", "Arapça", True, True),
    ("Mustafa", "Arapça", True, True),
    ("Mutlu", "Türkçe", True, False),
    ("Muzaffer", "Arapça", True, True),
    ("Müfit", "Arapça", False, True),
    ("Münir", "Arapça", False, True),
    ("Müslüm", "Arapça", True, True),

    # N harfi
    ("Nabi", "Arapça", False, True),
    ("Naci", "Arapça", False, True),
    ("Nadir", "Arapça", False, True),
    ("Nafiz", "Arapça", False, True),
    ("Nail", "Arapça", False, True),
    ("Naim", "Arapça", False, True),
    ("Namık", "Arapça", False, True),
    ("Nazif", "Arapça", False, True),
    ("Nazım", "Arapça", True, True),
    ("Necati", "Arapça", True, True),
    ("Necdet", "Arapça", True, True),
    ("Necip", "Arapça", True, True),
    ("Necmettin", "Arapça", False, True),
    ("Nedim", "Arapça", True, True),
    ("Nejat", "Arapça", True, True),
    ("Neşet", "Arapça", False, True),
    ("Nevzat", "Farsça", True, False),
    ("Nihat", "Arapça", True, True),
    ("Niyazi", "Arapça", True, True),
    ("Nuh", "Arapça", True, True),
    ("Numan", "Arapça", True, True),
    ("Nureddin", "Arapça", False, True),
    ("Nurettin", "Arapça", False, True),
    ("Nuri", "Arapça", True, True),
    ("Nurullah", "Arapça", True, True),

    # O-Ö harfi
    ("Oğuz", "Türkçe", True, False),
    ("Oğuzalp", "Türkçe", False, False),
    ("Oğuzhan", "Türkçe", True, False),
    ("Okan", "Türkçe", True, False),
    ("Oktar", "Türkçe", False, False),
    ("Oktay", "Türkçe", True, False),
    ("Olcay", "Türkçe", True, False),
    ("Olgun", "Türkçe", True, False),
    ("Oluç", "Türkçe", False, False),
    ("Onur", "Türkçe", True, False),
    ("Oruç", "Türkçe", False, True),
    ("Osman", "Arapça", True, True),
    ("Ömer", "Arapça", True, True),
    ("Önay", "Türkçe", False, False),
    ("Önder", "Türkçe", True, False),
    ("Öner", "Türkçe", False, False),
    ("Özalp", "Türkçe", False, False),
    ("Özay", "Türkçe", False, False),
    ("Özcan", "Türkçe", True, False),
    ("Özdemir", "Türkçe", True, False),
    ("Özer", "Türkçe", True, False),
    ("Özgür", "Türkçe", True, False),
    ("Özhan", "Türkçe", True, False),
    ("Özkan", "Türkçe", True, False),
    ("Öztürk", "Türkçe", True, False),

    # P harfi
    ("Pamir", "Türkçe", False, False),
    ("Pars", "Türkçe", False, False),
    ("Peker", "Türkçe", False, False),
    ("Peyami", "Farsça", False, False),
    ("Polat", "Türkçe", True, False),
    ("Polathan", "Türkçe", False, False),

    # R harfi
    ("Rafet", "Arapça", False, True),
    ("Ragıp", "Arapça", False, True),
    ("Rahmi", "Arapça", False, True),
    ("Raif", "Arapça", False, True),
    ("Ramadan", "Arapça", False, True),
    ("Ramazan", "Arapça", True, True),
    ("Rasim", "Arapça", False, True),
    ("Recai", "Arapça", False, True),
    ("Recep", "Arapça", True, True),
    ("Refik", "Arapça", False, True),
    ("Remzi", "Arapça", True, True),
    ("Reşat", "Arapça", False, True),
    ("Rıdvan", "Arapça", True, True),
    ("Rıfat", "Arapça", True, True),
    ("Rıza", "Arapça", True, True),
    ("Rüştü", "Arapça", False, True),

    # S-Ş harfi
    ("Sabir", "Arapça", False, True),
    ("Sabri", "Arapça", True, True),
    ("Sacit", "Arapça", False, True),
    ("Sadık", "Arapça", True, True),
    ("Sadri", "Arapça", False, True),
    ("Sadullah", "Arapça", False, True),
    ("Saffet", "Arapça", False, True),
    ("Said", "Arapça", True, True),
    ("Saim", "Arapça", False, True),
    ("Sait", "Arapça", True, True),
    ("Salih", "Arapça", True, True),
    ("Salim", "Arapça", True, True),
    ("Sami", "Arapça", True, True),
    ("Samet", "Arapça", True, True),
    ("Sancak", "Türkçe", False, False),
    ("Saner", "Türkçe", False, False),
    ("Saruhan", "Türkçe", False, False),
    ("Savaş", "Türkçe", True, False),
    ("Sedat", "Arapça", True, True),
    ("Sefer", "Arapça", False, True),
    ("Selami", "Arapça", True, True),
    ("Selçuk", "Türkçe", True, False),
    ("Selim", "Arapça", True, True),
    ("Selman", "Arapça", True, True),
    ("Semih", "Arapça", True, True),
    ("Semir", "Arapça", False, True),
    ("Sercan", "Türkçe", True, False),
    ("Serdar", "Farsça", True, False),
    ("Seref", "Arapça", True, True),
    ("Sergen", "Türkçe", True, False),
    ("Serhan", "Türkçe", True, False),
    ("Serhat", "Türkçe", True, False),
    ("Serkan", "Türkçe", True, False),
    ("Sertan", "Türkçe", False, False),
    ("Sertaç", "Türkçe", True, False),
    ("Server", "Farsça", False, False),
    ("Servet", "Arapça", True, True),
    ("Seyfi", "Arapça", False, True),
    ("Seyhan", "Türkçe", False, False),
    ("Seyit", "Arapça", True, True),
    ("Sezai", "Arapça", True, True),
    ("Sezgin", "Türkçe", True, False),
    ("Sinan", "Arapça", True, True),
    ("Soner", "Türkçe", True, False),
    ("Suat", "Arapça", True, True),
    ("Süha", "Arapça", False, True),
    ("Süleyman", "Arapça", True, True),
    ("Sünay", "Türkçe", False, False),
    ("Şaban", "Arapça", True, True),
    ("Şafak", "Türkçe", True, False),
    ("Şahin", "Türkçe", True, False),
    ("Şakir", "Arapça", False, True),
    ("Şamil", "Arapça", False, True),
    ("Şanal", "Türkçe", False, False),
    ("Şefik", "Arapça", False, True),
    ("Şemseddin", "Arapça", False, True),
    ("Şener", "Türkçe", True, False),
    ("Şenol", "Türkçe", True, False),
    ("Şerafettin", "Arapça", False, True),
    ("Şeref", "Arapça", True, True),
    ("Şevket", "Arapça", True, True),
    ("Şükrü", "Arapça", True, True),

    # T harfi
    ("Tacettin", "Arapça", False, True),
    ("Tahir", "Arapça", True, True),
    ("Tahsin", "Arapça", True, True),
    ("Talat", "Arapça", False, True),
    ("Talha", "Arapça", True, True),
    ("Talip", "Arapça", False, True),
    ("Tamer", "Türkçe", True, False),
    ("Taner", "Türkçe", True, False),
    ("Tanrıverdi", "Türkçe", False, False),
    ("Tansel", "Türkçe", False, False),
    ("Tarık", "Arapça", True, True),
    ("Tayfun", "Türkçe", True, False),
    ("Tayfur", "Arapça", False, True),
    ("Taylan", "Türkçe", True, False),
    ("Tekin", "Türkçe", True, False),
    ("Temel", "Türkçe", True, False),
    ("Teoman", "Türkçe", True, False),
    ("Tevfik", "Arapça", True, True),
    ("Timur", "Türkçe", True, False),
    ("Timuçin", "Türkçe", False, False),
    ("Tolga", "Türkçe", True, False),
    ("Tolunay", "Türkçe", False, False),
    ("Tufan", "Arapça", True, True),
    ("Tugay", "Türkçe", True, False),
    ("Tuğrul", "Türkçe", True, False),
    ("Tuncay", "Türkçe", True, False),
    ("Tuncer", "Türkçe", True, False),
    ("Tunahan", "Türkçe", True, False),
    ("Turan", "Türkçe", True, False),
    ("Turgay", "Türkçe", True, False),
    ("Turgut", "Türkçe", True, False),
    ("Turhan", "Türkçe", True, False),
    ("Türkay", "Türkçe", False, False),
    ("Türker", "Türkçe", True, False),

    # U-Ü harfi
    ("Uğur", "Türkçe", True, False),
    ("Uğurcan", "Türkçe", False, False),
    ("Ufuk", "Türkçe", True, False),
    ("Ulaş", "Türkçe", True, False),
    ("Ulvi", "Arapça", False, True),
    ("Umut", "Türkçe", True, False),
    ("Utku", "Türkçe", True, False),
    ("Übeyt", "Arapça", False, True),
    ("Ümit", "Türkçe", True, False),
    ("Ünal", "Türkçe", True, False),

    # V harfi
    ("Vahap", "Arapça", False, True),
    ("Vahdettin", "Arapça", False, True),
    ("Vahit", "Arapça", False, True),
    ("Vecdi", "Arapça", False, True),
    ("Vehbi", "Arapça", False, True),
    ("Veli", "Arapça", True, True),
    ("Velit", "Arapça", False, True),
    ("Veysel", "Arapça", True, True),
    ("Volkan", "Türkçe", True, False),

    # Y harfi
    ("Yahya", "Arapça", True, True),
    ("Yakup", "Arapça", True, True),
    ("Yalçın", "Türkçe", True, False),
    ("Yaman", "Türkçe", True, False),
    ("Yamaç", "Türkçe", True, False),
    ("Yasin", "Arapça", True, True),
    ("Yaşar", "Türkçe", True, False),
    ("Yavuz", "Türkçe", True, False),
    ("Yekta", "Farsça", False, False),
    ("Yener", "Türkçe", True, False),
    ("Yetkin", "Türkçe", False, False),
    ("Yıldırım", "Türkçe", True, False),
    ("Yıldız", "Türkçe", True, False),
    ("Yılmaz", "Türkçe", True, False),
    ("Yiğit", "Türkçe", True, False),
    ("Yiğitcan", "Türkçe", True, False),
    ("Yiğithan", "Türkçe", False, False),
    ("Yunus", "Arapça", True, True),
    ("Yusuf", "Arapça", True, True),
    ("Yücel", "Türkçe", True, False),

    # Z harfi
    ("Zafer", "Arapça", True, True),
    ("Zahit", "Arapça", False, True),
    ("Zeki", "Arapça", True, True),
    ("Zekeriya", "Arapça", True, True),
    ("Zeynel", "Arapça", False, True),
    ("Zihni", "Arapça", False, True),
    ("Ziya", "Arapça", True, True),
    ("Zülfikar", "Arapça", False, True),
    ("Zülfü", "Arapça", False, True),
]

KIZ_ISIMLERI = [
    # A harfi
    ("Açelya", "Türkçe", True, False),
    ("Ada", "Türkçe", True, False),
    ("Adile", "Arapça", False, True),
    ("Adviye", "Arapça", False, True),
    ("Afet", "Arapça", False, False),
    ("Afife", "Arapça", False, True),
    ("Afiyet", "Arapça", False, True),
    ("Afra", "Arapça", True, True),
    ("Ahu", "Farsça", False, False),
    ("Ahsen", "Arapça", False, True),
    ("Aişe", "Arapça", False, True),
    ("Ajda", "Farsça", False, False),
    ("Akasya", "Diğer", False, False),
    ("Akgül", "Türkçe", False, False),
    ("Alara", "Türkçe", True, False),
    ("Alanur", "Türkçe", False, False),
    ("Aleyna", "Arapça", True, True),
    ("Alev", "Türkçe", True, False),
    ("Algın", "Türkçe", False, False),
    ("Aliye", "Arapça", False, True),
    ("Almila", "Türkçe", True, False),
    ("Alsu", "Türkçe", False, False),
    ("Anıl", "Türkçe", False, False),
    ("Arife", "Arapça", False, True),
    ("Arzu", "Farsça", True, False),
    ("Asel", "Türkçe", True, False),
    ("Asena", "Türkçe", True, False),
    ("Aslı", "Türkçe", True, False),
    ("Aslıhan", "Türkçe", True, False),
    ("Asuman", "Farsça", True, False),
    ("Asya", "Diğer", True, False),
    ("Ateş", "Türkçe", False, False),
    ("Atiye", "Arapça", False, True),
    ("Aybeniz", "Türkçe", False, False),
    ("Ayça", "Türkçe", True, False),
    ("Ayçin", "Türkçe", False, False),
    ("Ayda", "Türkçe", True, False),
    ("Aydan", "Türkçe", True, False),
    ("Aydanur", "Türkçe", False, False),
    ("Ayfer", "Türkçe", True, False),
    ("Aygül", "Türkçe", True, False),
    ("Aygün", "Türkçe", False, False),
    ("Ayhan", "Türkçe", False, False),
    ("Ayla", "Türkçe", True, False),
    ("Aylin", "Türkçe", True, False),
    ("Aynur", "Türkçe", True, False),
    ("Ayris", "Türkçe", False, False),
    ("Aysel", "Türkçe", True, False),
    ("Aysen", "Türkçe", True, False),
    ("Ayşe", "Arapça", True, True),
    ("Ayşegül", "Türkçe", True, False),
    ("Ayşen", "Türkçe", True, False),
    ("Ayşenur", "Türkçe", True, True),
    ("Ayşin", "Türkçe", False, False),
    ("Ayten", "Türkçe", True, False),
    ("Azade", "Farsça", False, False),
    ("Azime", "Arapça", False, True),
    ("Azize", "Arapça", False, True),
    ("Azra", "Arapça", True, True),

    # B harfi
    ("Bahar", "Farsça", True, False),
    ("Bahire", "Arapça", False, True),
    ("Banu", "Farsça", True, False),
    ("Başak", "Türkçe", True, False),
    ("Bedia", "Arapça", False, True),
    ("Begüm", "Türkçe", True, False),
    ("Behice", "Arapça", False, True),
    ("Behire", "Arapça", False, True),
    ("Belgin", "Türkçe", True, False),
    ("Belkıs", "Arapça", False, True),
    ("Belma", "Türkçe", False, False),
    ("Belmira", "Diğer", False, False),
    ("Bengi", "Türkçe", False, False),
    ("Bengisu", "Türkçe", True, False),
    ("Bengü", "Türkçe", True, False),
    ("Bennu", "Arapça", False, True),
    ("Berceste", "Farsça", False, False),
    ("Beren", "Türkçe", True, False),
    ("Beril", "Türkçe", True, False),
    ("Berin", "Türkçe", True, False),
    ("Berivan", "Türkçe", False, False),
    ("Berrin", "Türkçe", True, False),
    ("Beste", "Türkçe", True, False),
    ("Betül", "Arapça", True, True),
    ("Beyhan", "Türkçe", True, False),
    ("Beyza", "Arapça", True, True),
    ("Bihter", "Farsça", False, False),
    ("Bilge", "Türkçe", True, False),
    ("Birgül", "Türkçe", True, False),
    ("Birsen", "Türkçe", True, False),
    ("Bişeng", "Farsça", False, False),
    ("Burcu", "Türkçe", True, False),
    ("Burçak", "Türkçe", True, False),
    ("Burçin", "Türkçe", True, False),
    ("Büşra", "Arapça", True, True),

    # C-Ç harfi
    ("Cahide", "Arapça", False, True),
    ("Canan", "Farsça", True, False),
    ("Candan", "Farsça", True, False),
    ("Cangül", "Türkçe", False, False),
    ("Cansu", "Türkçe", True, False),
    ("Cansun", "Türkçe", False, False),
    ("Canyüce", "Türkçe", False, False),
    ("Cemile", "Arapça", False, True),
    ("Cemre", "Türkçe", True, False),
    ("Cennet", "Arapça", True, True),
    ("Ceren", "Türkçe", True, False),
    ("Ceyla", "Türkçe", True, False),
    ("Ceylan", "Türkçe", True, False),
    ("Ceylin", "Türkçe", True, False),
    ("Ceyda", "Türkçe", True, False),
    ("Ciğdem", "Türkçe", False, False),
    ("Cihan", "Farsça", False, False),
    ("Cilve", "Arapça", False, False),
    ("Çağla", "Türkçe", True, False),
    ("Çiçek", "Türkçe", True, False),
    ("Çiğdem", "Türkçe", True, False),
    ("Çimen", "Türkçe", True, False),
    ("Çınay", "Türkçe", False, False),
    ("Çise", "Türkçe", False, False),
    ("Çisem", "Türkçe", False, False),
    ("Çisil", "Türkçe", False, False),

    # D harfi
    ("Damla", "Türkçe", True, False),
    ("Defne", "Türkçe", True, False),
    ("Deniz", "Türkçe", True, False),
    ("Derya", "Türkçe", True, False),
    ("Destan", "Türkçe", False, False),
    ("Dide", "Farsça", False, False),
    ("Didem", "Farsça", True, False),
    ("Didik", "Türkçe", False, False),
    ("Dilay", "Türkçe", True, False),
    ("Dilara", "Farsça", True, False),
    ("Dilay", "Türkçe", True, False),
    ("Dilber", "Farsça", True, False),
    ("Dildade", "Farsça", False, False),
    ("Dilek", "Türkçe", True, False),
    ("Dilhan", "Farsça", False, False),
    ("Dilruba", "Farsça", False, False),
    ("Dilşad", "Farsça", False, False),
    ("Dina", "Arapça", False, True),
    ("Dolunay", "Türkçe", True, False),
    ("Döndü", "Türkçe", False, False),
    ("Dua", "Arapça", True, True),
    ("Duygu", "Türkçe", True, False),

    # E harfi
    ("Ebrar", "Arapça", True, True),
    ("Ebru", "Türkçe", True, False),
    ("Ece", "Türkçe", True, False),
    ("Ecrin", "Arapça", True, True),
    ("Eda", "Türkçe", True, False),
    ("Edibe", "Arapça", False, True),
    ("Eflin", "Türkçe", False, False),
    ("Efsa", "Türkçe", False, False),
    ("Efsane", "Farsça", True, False),
    ("Efsun", "Farsça", True, False),
    ("Ela", "Türkçe", True, False),
    ("Elanur", "Türkçe", True, True),
    ("Elçin", "Türkçe", True, False),
    ("Elçin", "Türkçe", True, False),
    ("Elif", "Arapça", True, True),
    ("Eliz", "Diğer", True, False),
    ("Elmas", "Türkçe", True, False),
    ("Emel", "Türkçe", True, False),
    ("Emine", "Arapça", True, True),
    ("Emire", "Arapça", False, True),
    ("Enise", "Arapça", False, True),
    ("Erbay", "Türkçe", False, False),
    ("Ergül", "Türkçe", False, False),
    ("Eril", "Türkçe", False, False),
    ("Erin", "Türkçe", False, False),
    ("Erva", "Arapça", True, True),
    ("Esila", "Türkçe", True, False),
    ("Eslem", "Türkçe", True, False),
    ("Esma", "Arapça", True, True),
    ("Esmeray", "Türkçe", True, False),
    ("Esra", "Arapça", True, True),
    ("Evin", "Türkçe", False, False),
    ("Evlin", "Türkçe", False, False),
    ("Evra", "Türkçe", False, False),
    ("Evren", "Türkçe", True, False),
    ("Evrim", "Türkçe", True, False),
    ("Eylül", "Türkçe", True, False),
    ("Ezgi", "Türkçe", True, False),

    # F harfi
    ("Fadik", "Türkçe", False, False),
    ("Fadime", "Arapça", True, True),
    ("Fahriye", "Arapça", False, True),
    ("Fahrunisa", "Arapça", False, True),
    ("Faika", "Arapça", False, True),
    ("Faize", "Arapça", False, True),
    ("Fani", "Arapça", False, True),
    ("Farah", "Arapça", False, True),
    ("Farida", "Arapça", False, True),
    ("Fatma", "Arapça", True, True),
    ("Fatmagül", "Türkçe", False, False),
    ("Fatoş", "Türkçe", True, False),
    ("Fazilet", "Arapça", True, True),
    ("Ferah", "Arapça", False, True),
    ("Ferda", "Farsça", True, False),
    ("Feride", "Arapça", True, True),
    ("Feriha", "Arapça", False, True),
    ("Feryal", "Arapça", False, True),
    ("Fethiye", "Arapça", False, True),
    ("Fevziye", "Arapça", False, True),
    ("Feyza", "Arapça", True, True),
    ("Fidan", "Türkçe", True, False),
    ("Figen", "Farsça", True, False),
    ("Fikriye", "Arapça", False, True),
    ("Filiz", "Türkçe", True, False),
    ("Firdevs", "Farsça", False, True),
    ("Fulya", "Diğer", True, False),
    ("Funda", "Türkçe", True, False),

    # G harfi
    ("Gamze", "Türkçe", True, False),
    ("Gaye", "Arapça", True, True),
    ("Gizem", "Türkçe", True, False),
    ("Gökben", "Türkçe", False, False),
    ("Gökçe", "Türkçe", True, False),
    ("Gökçen", "Türkçe", True, False),
    ("Göknur", "Türkçe", True, False),
    ("Göksu", "Türkçe", True, False),
    ("Gökşen", "Türkçe", False, False),
    ("Gönül", "Türkçe", True, False),
    ("Gözde", "Türkçe", True, False),
    ("Gül", "Türkçe", True, False),
    ("Gülay", "Türkçe", True, False),
    ("Gülbahar", "Türkçe", True, False),
    ("Gülben", "Türkçe", True, False),
    ("Gülcan", "Türkçe", True, False),
    ("Gülçin", "Türkçe", True, False),
    ("Gülden", "Türkçe", True, False),
    ("Gülen", "Türkçe", True, False),
    ("Güler", "Türkçe", True, False),
    ("Gülfem", "Türkçe", True, False),
    ("Gülhan", "Türkçe", True, False),
    ("Gülizar", "Farsça", True, False),
    ("Gülnaz", "Farsça", True, False),
    ("Gülnur", "Türkçe", True, False),
    ("Gülperi", "Farsça", True, False),
    ("Gülriz", "Farsça", False, False),
    ("Gülsen", "Türkçe", True, False),
    ("Gülseren", "Türkçe", True, False),
    ("Gülser", "Türkçe", True, False),
    ("Gülsüm", "Arapça", True, True),
    ("Gülten", "Türkçe", True, False),
    ("Gülüm", "Türkçe", True, False),
    ("Gülümser", "Türkçe", False, False),
    ("Günay", "Türkçe", True, False),
    ("Güneş", "Türkçe", True, False),
    ("Günsel", "Türkçe", True, False),
    ("Günşen", "Türkçe", False, False),
    ("Güral", "Türkçe", False, False),
    ("Güray", "Türkçe", False, False),

    # H harfi
    ("Hacer", "Arapça", True, True),
    ("Hafize", "Arapça", False, True),
    ("Hale", "Arapça", True, True),
    ("Halide", "Arapça", False, True),
    ("Halime", "Arapça", True, True),
    ("Hamide", "Arapça", False, True),
    ("Handan", "Farsça", True, False),
    ("Hande", "Farsça", True, False),
    ("Hanife", "Arapça", True, True),
    ("Hanım", "Türkçe", True, False),
    ("Hasibe", "Arapça", False, True),
    ("Hasret", "Türkçe", True, False),
    ("Hatice", "Arapça", True, True),
    ("Havva", "Arapça", True, True),
    ("Hayat", "Arapça", True, True),
    ("Hayriye", "Arapça", True, True),
    ("Hazan", "Türkçe", True, False),
    ("Hazal", "Türkçe", True, False),
    ("Hicran", "Arapça", True, True),
    ("Hilal", "Arapça", True, True),
    ("Hira", "Arapça", True, True),
    ("Hümeyra", "Arapça", True, True),
    ("Huri", "Arapça", False, True),
    ("Huriye", "Arapça", False, True),
    ("Hüda", "Arapça", False, True),
    ("Hülya", "Türkçe", True, False),
    ("Hümeyra", "Arapça", True, True),
    ("Hüsna", "Arapça", False, True),
    ("Hüsniye", "Arapça", False, True),

    # I-İ harfi
    ("Ilgın", "Türkçe", True, False),
    ("Ilgaz", "Türkçe", False, False),
    ("Ilay", "Türkçe", True, False),
    ("Ilayda", "Türkçe", True, False),
    ("Işık", "Türkçe", True, False),
    ("Işıl", "Türkçe", True, False),
    ("Işın", "Türkçe", True, False),
    ("İclal", "Arapça", False, True),
    ("İdil", "Türkçe", True, False),
    ("İffet", "Arapça", False, True),
    ("İkbal", "Arapça", False, True),
    ("İkranur", "Türkçe", True, True),
    ("İlayda", "Türkçe", True, False),
    ("İlgin", "Türkçe", True, False),
    ("İlke", "Türkçe", True, False),
    ("İlkay", "Türkçe", True, False),
    ("İlke", "Türkçe", True, False),
    ("İlknur", "Türkçe", True, False),
    ("İlknaz", "Türkçe", False, False),
    ("İlksen", "Türkçe", False, False),
    ("İlksu", "Türkçe", False, False),
    ("İmge", "Türkçe", True, False),
    ("İnci", "Türkçe", True, False),
    ("İpek", "Türkçe", True, False),
    ("İrem", "Türkçe", True, False),
    ("İris", "Diğer", False, False),

    # K harfi
    ("Kader", "Arapça", True, True),
    ("Kadriye", "Arapça", True, True),
    ("Kamile", "Arapça", False, True),
    ("Kardelen", "Türkçe", True, False),
    ("Katre", "Arapça", False, True),
    ("Kayra", "Türkçe", True, False),
    ("Kevser", "Arapça", True, True),
    ("Kıymet", "Türkçe", True, False),
    ("Kiraz", "Türkçe", True, False),
    ("Kübra", "Arapça", True, True),

    # L harfi
    ("Lale", "Farsça", True, False),
    ("Lamia", "Arapça", False, True),
    ("Latife", "Arapça", False, True),
    ("Leyla", "Arapça", True, True),
    ("Leman", "Farsça", True, False),
    ("Lena", "Diğer", True, False),
    ("Lila", "Farsça", False, False),
    ("Lina", "Arapça", True, True),
    ("Lora", "Diğer", False, False),
    ("Lütfiye", "Arapça", False, True),

    # M harfi
    ("Maide", "Arapça", False, True),
    ("Makbule", "Arapça", False, True),
    ("Maral", "Türkçe", True, False),
    ("Maviş", "Türkçe", False, False),
    ("Maya", "Türkçe", True, False),
    ("Mebrure", "Arapça", False, True),
    ("Mediha", "Arapça", False, True),
    ("Medine", "Arapça", False, True),
    ("Mehtap", "Türkçe", True, False),
    ("Melahat", "Arapça", False, True),
    ("Melek", "Arapça", True, True),
    ("Melekber", "Türkçe", False, False),
    ("Melike", "Arapça", True, True),
    ("Melis", "Türkçe", True, False),
    ("Melisa", "Diğer", True, False),
    ("Melodi", "Diğer", True, False),
    ("Meltem", "Türkçe", True, False),
    ("Meral", "Farsça", True, False),
    ("Meriç", "Türkçe", True, False),
    ("Merih", "Arapça", False, True),
    ("Merve", "Arapça", True, True),
    ("Meryem", "Arapça", True, True),
    ("Mevsim", "Türkçe", False, False),
    ("Mina", "Türkçe", True, False),
    ("Mine", "Türkçe", True, False),
    ("Miray", "Türkçe", True, False),
    ("Misel", "Diğer", False, False),
    ("Muazzez", "Arapça", False, True),
    ("Muhlise", "Arapça", False, True),
    ("Mukaddes", "Arapça", False, True),
    ("Munise", "Arapça", False, True),
    ("Müberra", "Arapça", False, True),
    ("Mübeccel", "Arapça", False, True),
    ("Müesser", "Arapça", False, True),
    ("Müfide", "Arapça", False, True),
    ("Müge", "Türkçe", True, False),
    ("Mühibe", "Arapça", False, True),
    ("Müjde", "Türkçe", True, False),
    ("Müjgan", "Farsça", True, False),
    ("Mümine", "Arapça", False, True),
    ("Münire", "Arapça", False, True),
    ("Münevver", "Arapça", False, True),
    ("Müşerref", "Arapça", False, True),

    # N harfi
    ("Naciye", "Arapça", False, True),
    ("Nagehan", "Farsça", True, False),
    ("Nagihan", "Farsça", True, False),
    ("Nahide", "Arapça", False, True),
    ("Naile", "Arapça", False, True),
    ("Naime", "Arapça", False, True),
    ("Nalan", "Farsça", True, False),
    ("Narin", "Türkçe", True, False),
    ("Nazan", "Farsça", True, False),
    ("Nazife", "Arapça", False, True),
    ("Nazik", "Arapça", False, True),
    ("Nazire", "Arapça", False, True),
    ("Nazlı", "Türkçe", True, False),
    ("Nazlıcan", "Türkçe", True, False),
    ("Nebile", "Arapça", False, True),
    ("Necat", "Arapça", False, True),
    ("Neclâ", "Arapça", False, True),
    ("Necmiye", "Arapça", False, True),
    ("Nefise", "Arapça", False, True),
    ("Nehir", "Türkçe", True, False),
    ("Neriman", "Farsça", True, False),
    ("Nermin", "Farsça", True, False),
    ("Neslihan", "Türkçe", True, False),
    ("Nesrin", "Farsça", True, False),
    ("Neşe", "Türkçe", True, False),
    ("Neva", "Farsça", True, False),
    ("Nevin", "Farsça", True, False),
    ("Nevra", "Farsça", False, False),
    ("Neziha", "Arapça", False, True),
    ("Nigar", "Farsça", True, False),
    ("Nihal", "Farsça", True, False),
    ("Nihan", "Farsça", True, False),
    ("Nil", "Diğer", True, False),
    ("Nilay", "Türkçe", True, False),
    ("Nilgün", "Türkçe", True, False),
    ("Nilhan", "Türkçe", False, False),
    ("Nilüfer", "Farsça", True, False),
    ("Nisa", "Arapça", True, True),
    ("Nisan", "Türkçe", True, False),
    ("Nişan", "Türkçe", False, False),
    ("Nuran", "Arapça", True, True),
    ("Nuray", "Türkçe", True, False),
    ("Nurcan", "Türkçe", True, False),
    ("Nurdan", "Türkçe", True, False),
    ("Nurgül", "Türkçe", True, False),
    ("Nurhan", "Türkçe", True, False),
    ("Nuriye", "Arapça", True, True),
    ("Nurseli", "Türkçe", True, False),
    ("Nursel", "Türkçe", True, False),
    ("Nursema", "Türkçe", False, False),
    ("Nursen", "Türkçe", True, False),
    ("Nursev", "Türkçe", False, False),
    ("Nursima", "Türkçe", False, False),
    ("Nurten", "Türkçe", True, False),

    # O-Ö harfi
    ("Oya", "Türkçe", True, False),
    ("Oylum", "Türkçe", False, False),
    ("Özden", "Türkçe", True, False),
    ("Özge", "Türkçe", True, False),
    ("Özgül", "Türkçe", True, False),
    ("Özgür", "Türkçe", True, False),
    ("Özlem", "Türkçe", True, False),
    ("Öznur", "Türkçe", True, False),
    ("Özüm", "Türkçe", False, False),

    # P harfi
    ("Pakize", "Farsça", False, False),
    ("Pamuk", "Türkçe", False, False),
    ("Pelin", "Türkçe", True, False),
    ("Pembe", "Türkçe", True, False),
    ("Peri", "Farsça", True, False),
    ("Perihan", "Farsça", True, False),
    ("Perin", "Farsça", True, False),
    ("Pervin", "Farsça", True, False),
    ("Perizat", "Farsça", False, False),
    ("Petek", "Türkçe", True, False),
    ("Pınar", "Türkçe", True, False),
    ("Piraye", "Farsça", False, False),

    # R harfi
    ("Rabia", "Arapça", True, True),
    ("Rafiye", "Arapça", False, True),
    ("Rahime", "Arapça", False, True),
    ("Raife", "Arapça", False, True),
    ("Rana", "Türkçe", True, False),
    ("Ravza", "Arapça", False, True),
    ("Raziye", "Arapça", False, True),
    ("Refika", "Arapça", False, True),
    ("Refia", "Arapça", False, True),
    ("Reyhan", "Farsça", True, False),
    ("Rezzan", "Türkçe", False, False),
    ("Rıdvana", "Arapça", False, True),
    ("Rojda", "Türkçe", False, False),
    ("Rüveyda", "Arapça", False, True),
    ("Rüya", "Türkçe", True, False),

    # S-Ş harfi
    ("Saadet", "Arapça", True, True),
    ("Sabire", "Arapça", False, True),
    ("Sabriye", "Arapça", False, True),
    ("Sacide", "Arapça", False, True),
    ("Sadi", "Arapça", False, True),
    ("Sadife", "Arapça", False, True),
    ("Sadiye", "Arapça", False, True),
    ("Safiye", "Arapça", False, True),
    ("Saime", "Arapça", False, True),
    ("Sakine", "Arapça", False, True),
    ("Saliha", "Arapça", True, True),
    ("Salime", "Arapça", False, True),
    ("Samime", "Arapça", False, True),
    ("Saniye", "Arapça", False, True),
    ("Sara", "Arapça", True, True),
    ("Saray", "Türkçe", False, False),
    ("Sare", "Arapça", True, True),
    ("Seda", "Türkçe", True, False),
    ("Sedef", "Türkçe", True, False),
    ("Sefa", "Arapça", True, True),
    ("Sefanur", "Türkçe", True, True),
    ("Seher", "Arapça", True, True),
    ("Sehernaz", "Farsça", False, False),
    ("Sel", "Türkçe", False, False),
    ("Selcan", "Türkçe", True, False),
    ("Selda", "Türkçe", True, False),
    ("Selen", "Türkçe", True, False),
    ("Selin", "Türkçe", True, False),
    ("Selma", "Türkçe", True, False),
    ("Selmin", "Türkçe", False, False),
    ("Selva", "Türkçe", True, False),
    ("Selvi", "Türkçe", True, False),
    ("Sema", "Arapça", True, True),
    ("Semanur", "Türkçe", True, True),
    ("Semra", "Türkçe", True, False),
    ("Sena", "Arapça", True, True),
    ("Senanur", "Türkçe", True, True),
    ("Serap", "Türkçe", True, False),
    ("Seren", "Türkçe", True, False),
    ("Serenay", "Türkçe", True, False),
    ("Serin", "Türkçe", True, False),
    ("Serpil", "Türkçe", True, False),
    ("Sevcan", "Türkçe", True, False),
    ("Sevda", "Türkçe", True, False),
    ("Sevde", "Arapça", True, True),
    ("Sevgi", "Türkçe", True, False),
    ("Sevil", "Türkçe", True, False),
    ("Sevim", "Türkçe", True, False),
    ("Sevin", "Türkçe", True, False),
    ("Sevinç", "Türkçe", True, False),
    ("Seyyal", "Arapça", False, True),
    ("Sıdıka", "Arapça", False, True),
    ("Sibel", "Türkçe", True, False),
    ("Sıla", "Türkçe", True, False),
    ("Simay", "Türkçe", True, False),
    ("Simge", "Türkçe", True, False),
    ("Sinem", "Türkçe", True, False),
    ("Siren", "Diğer", False, False),
    ("Sonay", "Türkçe", True, False),
    ("Songül", "Türkçe", True, False),
    ("Su", "Türkçe", True, False),
    ("Sudenaz", "Türkçe", True, False),
    ("Sudem", "Türkçe", False, False),
    ("Sude", "Arapça", True, True),
    ("Suhan", "Farsça", False, False),
    ("Suna", "Türkçe", True, False),
    ("Sunay", "Türkçe", True, False),
    ("Süheyla", "Arapça", False, True),
    ("Sükran", "Arapça", True, True),
    ("Sümeyra", "Arapça", True, True),
    ("Sümeyye", "Arapça", True, True),
    ("Şadiye", "Arapça", False, True),
    ("Şafak", "Türkçe", True, False),
    ("Şahika", "Arapça", False, True),
    ("Şahinde", "Farsça", False, False),
    ("Şahsenem", "Farsça", False, False),
    ("Şahnaz", "Farsça", False, False),
    ("Şebnem", "Farsça", True, False),
    ("Şefika", "Arapça", False, True),
    ("Şehriban", "Farsça", False, False),
    ("Şehrinaz", "Farsça", False, False),
    ("Şehriye", "Farsça", False, False),
    ("Şeker", "Türkçe", True, False),
    ("Şelale", "Farsça", False, False),
    ("Şenay", "Türkçe", True, False),
    ("Şengül", "Türkçe", True, False),
    ("Şennur", "Türkçe", False, False),
    ("Şerife", "Arapça", True, True),
    ("Şermin", "Farsça", True, False),
    ("Şeyda", "Farsça", True, False),
    ("Şeyma", "Arapça", True, True),
    ("Şilan", "Türkçe", False, False),
    ("Şirin", "Farsça", True, False),
    ("Şükran", "Arapça", True, True),
    ("Şükriye", "Arapça", False, True),
    ("Şule", "Arapça", True, True),

    # T harfi
    ("Tahire", "Arapça", False, True),
    ("Taliye", "Arapça", False, True),
    ("Tansu", "Türkçe", True, False),
    ("Tanem", "Türkçe", True, False),
    ("Tanyeli", "Türkçe", False, False),
    ("Tomris", "Türkçe", False, False),
    ("Tuba", "Arapça", True, True),
    ("Tuğba", "Arapça", True, True),
    ("Tuğçe", "Türkçe", True, False),
    ("Tülay", "Türkçe", True, False),
    ("Tülin", "Türkçe", True, False),
    ("Türkan", "Türkçe", True, False),

    # U-Ü harfi
    ("Ufuk", "Türkçe", False, False),
    ("Ulviye", "Arapça", False, True),
    ("Umay", "Türkçe", True, False),
    ("Umut", "Türkçe", True, False),
    ("Ülkü", "Türkçe", True, False),
    ("Ümran", "Arapça", False, True),
    ("Ümmühan", "Arapça", False, True),
    ("Ünzile", "Arapça", False, True),

    # V harfi
    ("Vahide", "Arapça", False, True),
    ("Vasfiye", "Arapça", False, True),
    ("Vecihe", "Arapça", False, True),
    ("Vesile", "Arapça", False, True),

    # Y harfi
    ("Yağmur", "Türkçe", True, False),
    ("Yalın", "Türkçe", False, False),
    ("Yaprak", "Türkçe", True, False),
    ("Yaren", "Türkçe", True, False),
    ("Yasemin", "Farsça", True, False),
    ("Yaşam", "Türkçe", True, False),
    ("Yelda", "Farsça", True, False),
    ("Yeşim", "Türkçe", True, False),
    ("Yıldız", "Türkçe", True, False),
    ("Yonca", "Türkçe", True, False),
    ("Yosun", "Türkçe", False, False),
    ("Yüksel", "Türkçe", True, False),

    # Z harfi
    ("Zahide", "Arapça", False, True),
    ("Zara", "Türkçe", True, False),
    ("Zarife", "Arapça", False, True),
    ("Zehra", "Arapça", True, True),
    ("Zeliha", "Arapça", True, True),
    ("Zekiye", "Arapça", False, True),
    ("Zeliş", "Türkçe", False, False),
    ("Zerrin", "Farsça", True, False),
    ("Zeynep", "Arapça", True, True),
    ("Zilan", "Türkçe", False, False),
    ("Zinnur", "Arapça", False, True),
    ("Ziynet", "Arapça", False, True),
    ("Zuhal", "Arapça", True, True),
    ("Zübeyde", "Arapça", True, True),
    ("Zühal", "Arapça", True, True),
    ("Züleyha", "Arapça", True, True),
    ("Zülfiye", "Arapça", False, True),
    ("Zümra", "Türkçe", True, False),
    ("Zümrüt", "Türkçe", True, False),
]


def get_all_names():
    """Tüm isimleri döndür"""
    all_names = []

    # Unisex isimleri tespit et (her iki listede de olan isimler)
    erkek_set = {name[0] for name in ERKEK_ISIMLERI}
    kiz_set = {name[0] for name in KIZ_ISIMLERI}
    unisex_names = erkek_set.intersection(kiz_set)

    # Erkek isimlerini ekle
    for name_tuple in ERKEK_ISIMLERI:
        isim, koken, populer, islami = name_tuple
        cinsiyet = "unisex" if isim in unisex_names else "erkek"
        all_names.append({
            "isim": isim,
            "cinsiyet": cinsiyet,
            "koken": koken,
            "populer": populer,
            "islami": islami
        })

    # Kız isimlerini ekle (unisex olanları tekrar ekleme)
    for name_tuple in KIZ_ISIMLERI:
        isim, koken, populer, islami = name_tuple
        if isim not in unisex_names:  # Unisex ismi zaten erkek listesinden ekledik
            all_names.append({
                "isim": isim,
                "cinsiyet": "kiz",
                "koken": koken,
                "populer": populer,
                "islami": islami
            })

    return all_names


def get_names_by_gender(cinsiyet):
    """Cinsiyete göre isimleri döndür (unisex isimler her iki listede de çıkar)"""
    # Unisex isimleri tespit et
    erkek_set = {name[0] for name in ERKEK_ISIMLERI}
    kiz_set = {name[0] for name in KIZ_ISIMLERI}
    unisex_names = erkek_set.intersection(kiz_set)

    if cinsiyet == "erkek":
        # Erkek ve unisex isimleri döndür
        return [{"isim": n[0], "cinsiyet": "unisex" if n[0] in unisex_names else "erkek",
                 "koken": n[1], "populer": n[2], "islami": n[3]}
                for n in ERKEK_ISIMLERI]
    elif cinsiyet == "kiz":
        # Kız ve unisex isimleri döndür
        return [{"isim": n[0], "cinsiyet": "unisex" if n[0] in unisex_names else "kiz",
                 "koken": n[1], "populer": n[2], "islami": n[3]}
                for n in KIZ_ISIMLERI]
    return []


def get_names_by_origin(koken):
    """Kökene göre isimleri döndür"""
    all_names = get_all_names()
    return [n for n in all_names if n["koken"] == koken]


def get_popular_names():
    """Popüler isimleri döndür"""
    all_names = get_all_names()
    return [n for n in all_names if n["populer"]]


def get_islamic_names():
    """İslami isimleri döndür"""
    all_names = get_all_names()
    return [n for n in all_names if n["islami"]]


def get_name_count():
    """Toplam isim sayısını döndür"""
    return len(ERKEK_ISIMLERI) + len(KIZ_ISIMLERI)


if __name__ == "__main__":
    print(f"Toplam isim sayısı: {get_name_count()}")
    print(f"Erkek isim sayısı: {len(ERKEK_ISIMLERI)}")
    print(f"Kız isim sayısı: {len(KIZ_ISIMLERI)}")
    print(f"Popüler isim sayısı: {len(get_popular_names())}")
    print(f"İslami isim sayısı: {len(get_islamic_names())}")
